feet=int(input("enter the no of feets : "))
print("distance in feet :",feet)
print("distance in inches :",feet*12)
print("distance in yards :",feet*0.333333)
print("distance in miles :",feet/5280)
